Storage
String Storage::Name
Name of the Storage.
Referenced by getInfo, getName, add.
String Storage::Desc
Description of the Storage.
Referenced by getInfo, getDescription.
size_t Storage::MaxSize
Size of Storage, how many Item it can hold.
Referenced by getInfo, getMaxSize, setMaxSize, add.
GenericArray<Item> Storage::Items
Items in the Storage.
Referenced by getSize, getInfo, getInfoItems, getInfoItemsAll, getInfoItemsUse, getItems, isThereUpgrade, add, remove, clear, operator[].
Storage::Storage(const char *Name="BakPak", const char *Desc="This is a BakPak.", size_t MaxSize=5)
Default Constructor.
Storage::Storage(const Storage &S)
Copy Constructor.
Storage::~Storage()
Destructor.
std::ostream & Storage::getInfo(std::ostream &os=std::cout)
Writes out the Storage's info to the console.
References Desc, GenericArray< C >::getSize, Items, MaxSize, Name.
std::ostream & Storage::getInfoItems(InfoPreset Preset=InfoPreset(), std::ostream &os=std::cout)
Writes out the Item's infos in the Storage to the console.
References GenericArray< C >::getSize, Items.
std::ostream & Storage::getInfoItems(const ItemType &Type, InfoPreset Preset=InfoPreset(), std::ostream &os=std::cout)
Writes out a specific Item's infos in the Storage to the console.
References GenericArray< C >::getSize, Items.
std::ostream & Storage::getInfoItemsAll(std::ostream &os=std::cout)
Writes out the Item's infos in the Storage to the console.
References GenericArray< C >::getSize, Items.
Referenced by Player::getInfoEntity.
std::ostream & Storage::getInfoItemsAll(const ItemType &Type, std::ostream &os=std::cout)
Writes out a specific Item's infos in the Storage to the console.
References GenericArray< C >::getSize, Items.
std::ostream & Storage::getInfoItemsUse(std::ostream &os=std::cout)
Writes out the Item's infos in the Storage to the console.
References GenericArray< C >::getSize, Items.
std::ostream & Storage::getInfoItemsUse(const ItemType &Type, std::ostream &os=std::cout)
Writes out a specific Item's infos in the Storage to the console.
References GenericArray< C >::getSize, Items.
const char * Storage::getName()
Gets Name.
References String::getStr, Name.
Referenced by Player::getInfoEntity.
const char * Storage::getDescription()
Gets Description.
References Desc, String::getStr.
GenericArray< Item > Storage::getItems() const
Gets the Item's array, though cannot modify it.
References Items.
void Storage::add(const Item &Element)
Adds an Item to the Storage.
References GenericArray< C >::add, GenericArray< C >::getSize, Items, MaxSize, Name.
void Storage::remove(const size_t &Index)
Removes an Item from the Storage according to its index.
References GenericArray< C >::getSize, Items, GenericArray< C >::remove.
Referenced by Player::Heal.
void Storage::clear()
Clears the Storage.
References GenericArray< C >::clear, Items.
size_t Storage::getMaxSize()
Gets size of Storage.
References MaxSize.
size_t Storage::getSize()
Gets number of Items in the of Storage.
References GenericArray< C >::getSize, Items.
void Storage::setMaxSize(const size_t &SizeC)
Sets size of Storage.
References MaxSize.
bool Storage::isThereUpgrade()
Returns if there are upgrades in the inventory.
References GenericArray< C >::getSize, Items.
Item& Storage::operator[](size_t Index) const
Accessing an Item as constant.
References Items.
Item& Storage::operator[](size_t Index)
Accessing an Item.
References Items.