Item
ItemType Item::Type
Type of the Item.
Referenced by getType, getInfoItems, useItem.
String Item::Name
Name of the Item.
Referenced by getName.
String Item::Desc
Description of the Item.
Referenced by getDesc.
double Item::BonusDMG
Additive Bonus Damage of Item.
Referenced by getBonusDMG.
double Item::BonusDMGM
Multiplied Bonus Damage of Item.
Referenced by getBonusDMGM.
double Item::BonusDEF
Additive Bonus Defense of Item.
Referenced by getBonusDEF.
double Item::BonusDEFM
Multiplied Bonus Defense of Item.
Referenced by getBonusDEFM.
double Item::Heal
Healing of Item.
Referenced by getHeal.
Item::Item(const ItemType Type=ItemType::WeaponShield, const char *Name="DisItem", const char *Desc="This is an Item.", const double &BonusDMG=0, const double &BonusDMGM=1, const double &BonusDEF=0, const double &BonusDEFM=1, const double &Heal=0)
Default Constructor.
Item::~Item()
Destructor.
std::ostream & Item::getInfoItems(InfoPreset Preset=InfoPreset(), std::ostream &os=std::cout)
Writes out the Item's info to an output.
References InfoPreset::DisplayNum, InfoPreset::Num, Type.
const char * Item::getName()
Gets Name.
References String::getStr, Name.
Referenced by Player::attackEnemy.
const char * Item::getDesc()
Gets Description.
References Desc, String::getStr.
double Item::getBonusDMG()
Gets Additive Bonus Damage of Item.
References BonusDMG.
Referenced by Player::attackEnemy.
double Item::getBonusDMGM()
Gets Multiplied Bonus Damage of Item.
References BonusDMGM.
Referenced by Player::attackEnemy.
double Item::getBonusDEF()
Gets Additive Bonus Defense of Item.
References BonusDEF.
Referenced by Player::attackEnemy, Enemy::attackPlayer.
double Item::getBonusDEFM()
Gets Multiplied Bonus Defense of Item.
References BonusDEFM.
Referenced by Player::attackEnemy, Enemy::attackPlayer.
double Item::getHeal()
Gets Healing of Item.
References Heal.
ItemType Item::getType() const
Gets Type of Item.
References Type.
Referenced by AttributeCheck< C >::operator().
UseCases Item::useItem()
Use an Item.
References Type.