Player
size_t Player::Gold
Amount of Gold the Player has.
Storage Player::StorageType
Storage of the Player.
Player::Player(const char *Name, double HP=100, double MaxHP=100, double BaseDMG=5, double BaseDEF=5, size_t Gold=0, Storage StorageType=Storage())
Constructor.
Player::Player(double HP=100, double MaxHP=100, double BaseDMG=5, double BaseDEF=5, size_t Gold=0)
Default Constructor.
Player::~Player()
Destructor.
std::ostream & Player::getInfoEntity(InfoPreset Preset=InfoPreset(), std::ostream &os=std::cout)
Writes out the Player's info to an output.
References InfoPreset::BaseDEF, InfoPreset::BaseDMG, Entity::getBaseDEF, Entity::getBaseDMG, getGold, Entity::getHP, Storage::getInfoItemsAll, Entity::getMaxHP, Entity::getName, Storage::getName, getStorageType, InfoPreset::Gold, InfoPreset::HP, InfoPreset::Items, InfoPreset::Name, InfoPreset::Storage.
size_t Player::getGold()
Gets Player's amount of Gold.
Referenced by getInfoEntity.
Storage & Player::getStorageType()
Gets Player's type of Storage.
Referenced by getInfoEntity, Heal.
void Player::attackEnemy(Enemy &e)
Attack an Enemy.
References Entity::getBaseDEF, Entity::getBaseDMG, Entity::getHP, Entity::getName, Entity::setHP.
void Player::attackEnemy(Enemy &e, Item &WS)
Attack an Enemy with a Weapon/Shield.
References Entity::getBaseDEF, Entity::getBaseDMG, Item::getBonusDEF, Item::getBonusDEFM, Item::getBonusDMG, Item::getBonusDMGM, Entity::getHP, Entity::getName, Item::getName, Entity::setHP.
void Player::Heal(const size_t Index)
Healing with an Item.
References Entity::getHP, Entity::getMaxHP, Entity::getName, getStorageType, Storage::remove, Entity::setHP.