GenericArray
C* GenericArray< C >::Array
size_t GenericArray< C >::Size
GenericArray< C >::GenericArray()
Default Constructor.
GenericArray< C >::GenericArray(const GenericArray< C > &GA)
Copy Constructor.
virtual GenericArray< C >::~GenericArray()
Destructor.
void GenericArray< C >::add(const C &Element)
Adding an Element to the Array.
Referenced by Storage::add.
void GenericArray< C >::remove(const size_t &Index)
Removes an Element from the Array.
Referenced by Storage::remove.
void GenericArray< C >::clear()
Clears (deletes and then reallocate) the Array.
Referenced by Storage::clear.
C& GenericArray< C >::operator[](size_t Index) const
Accessing Data as constant.
C& GenericArray< C >::operator[](size_t Index)
Accessing Data.
const size_t& GenericArray< C >::getSize()
Get Size of the Array.
Referenced by Storage::add, Storage::getInfo, Storage::getInfoItems, Storage::getInfoItemsAll, Storage::getInfoItemsUse, GenericArray< Item >::getPredNum, Storage::getSize, Storage::isThereUpgrade, Storage::remove.
size_t GenericArray< C >::getPredNum(Pred pred)
Get Number of specific Items in the Array.