Entity
String Entity::Name
Entity Name.
double Entity::HP
Healthpoint of the entity.
double Entity::MaxHP
Maximum Healthpoint of the entity.
double Entity::BaseDMG
Base Damage of the entity.
double Entity::BaseDEF
Base Defense of the entity.
Entity::Entity(const char *Name, double HP=100, double MaxHP=100, double BaseDMG=5, double BaseDEF=5)
Constructor.
Entity::Entity(double HP=100, double MaxHP=100, double BaseDMG=5, double BaseDEF=5)
Default Constructor.
Entity::~Entity()
Destructor.
const char * Entity::getName()
Gets Entity's name.
References String::getStr.
Referenced by Player::attackEnemy, Enemy::attackPlayer, Player::getInfoEntity, Enemy::getInfoEntity, Player::Heal.
double Entity::getBaseDMG()
Gets Entity's Base Damage.
Referenced by Player::attackEnemy, Enemy::attackPlayer, Player::getInfoEntity, Enemy::getInfoEntity.
double Entity::getBaseDEF()
Gets Entity's Base Defense.
Referenced by Player::attackEnemy, Enemy::attackPlayer, Player::getInfoEntity, Enemy::getInfoEntity.
double Entity::getHP()
Gets Entity's HP.
Referenced by Player::attackEnemy, Enemy::attackPlayer, Player::getInfoEntity, Enemy::getInfoEntity, Player::Heal.
double Entity::getMaxHP()
Gets Entity's MaxHP.
Referenced by Player::getInfoEntity, Enemy::getInfoEntity, Player::Heal.
void Entity::setHP(const double hp)
Sets Entity's HP.
Referenced by Player::attackEnemy, Enemy::attackPlayer, Player::Heal.
virtual std::ostream& Entity::getInfoEntity(InfoPreset Preset=InfoPreset(), std::ostream &os=std::cout)=0
Displays the info of an Entity, dynamically controlable with an InfoPreset.