String
char* String::pData
Data Pointer.
size_t String::len
Length of the string.
String::String(String const &str)
Copy Constructor.
Referenced by operator+.
String::String(const char *str="")
Default Constructor from const char*.
String::String(const char c)
Constructor from char.
virtual String::~String()
Destructor.
const char* String::getStr()
Return the content of the String.
Referenced by Item::getDesc, Storage::getDescription, Entity::getName, Item::getName, Storage::getName.
const size_t String::getSize()
Return the length of the String.
String & String::operator=(const String &rhs_s)
Assign the String's data to the String.
String & String::operator=(const char *rhs_s)
Assign const char*'s data to the String.
String& String::operator+=(const String &rhs_s)
Adding String to the original.
String String::operator+(const String &rhs_s) const
Adding 2 Strings together (returns constant)
String String::operator+(char rhs_c) const
Adding a char to the String (returns constant)
References String.