.TH "Y:/OneDrive VAQR_8066/OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség/Iskola/Prog2/NHF/Scars_Healing/IniGame.h" 3 "Sat May 2 2020" "Scars_Healing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Y:/OneDrive VAQR_8066/OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség/Iskola/Prog2/NHF/Scars_Healing/IniGame.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Item\&.h'\fP
.br
\fC#include 'GenericArray\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBGenericArray\fP< \fBItem\fP > \fBiniWS\fP (const char *WSPath='WeaponShield\&.txt')"
.br
.RI "Initializing WeaponShield Items from a file\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBGenericArray\fP<\fBItem\fP> iniWS (const char * WSPath = \fC'WeaponShield\&.txt'\fP)"

.PP
Initializing WeaponShield Items from a file\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Scars_Healing from the source code\&.
