.TH "Y:/OneDrive VAQR_8066/OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség/Iskola/Prog2/NHF/Scars_Healing/Item.h" 3 "Sat May 2 2020" "Scars_Healing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Y:/OneDrive VAQR_8066/OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség/Iskola/Prog2/NHF/Scars_Healing/Item.h
.SH SYNOPSIS
.br
.PP
\fC#include 'String\&.h'\fP
.br
\fC#include 'InfoPreset\&.h'\fP
.br
\fC#include 'GenericArray\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBItem\fP"
.br
.ti -1c
.RI "class \fBAttributeCheck< C >\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBItemType\fP { \fBItemType::WeaponShield\fP, \fBItemType::HealPotion\fP, \fBItemType::Vanity\fP, \fBItemType::WSUpgrade\fP }"
.br
.RI "Types of Items\&. "
.ti -1c
.RI "enum \fBUseCases\fP { \fBUseCases::Upgrade\fP, \fBUseCases::Drop\fP, \fBUseCases::Use\fP, \fBUseCases::Back\fP, \fBUseCases::Quit\fP, \fBUseCases::Info\fP, \fBUseCases::InvalidAction\fP, \fBUseCases::Heal\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBItemType\fP\fC [strong]\fP"

.PP
Types of Items\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIWeaponShield \fP\fP
.TP
\fB\fIHealPotion \fP\fP
.TP
\fB\fIVanity \fP\fP
.TP
\fB\fIWSUpgrade \fP\fP
.SS "enum \fBUseCases\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUpgrade \fP\fP
.TP
\fB\fIDrop \fP\fP
.TP
\fB\fIUse \fP\fP
.TP
\fB\fIBack \fP\fP
.TP
\fB\fIQuit \fP\fP
.TP
\fB\fIInfo \fP\fP
.TP
\fB\fIInvalidAction \fP\fP
.TP
\fB\fIHeal \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Scars_Healing from the source code\&.
