.TH "Y:/OneDrive VAQR_8066/OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség/Iskola/Prog2/NHF/Scars_Healing/main.cpp" 3 "Sat May 2 2020" "Scars_Healing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Y:/OneDrive VAQR_8066/OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség/Iskola/Prog2/NHF/Scars_Healing/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include 'memtrace\&.h'\fP
.br
\fC#include 'test\&.h'\fP
.br
\fC#include 'IniGame\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "Well, here we go\&.\&.\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Well, here we go\&.\&.\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Scars_Healing from the source code\&.
