.TH "Y:/OneDrive VAQR_8066/OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség/Iskola/Prog2/NHF/Scars_Healing/Player.h" 3 "Sat May 2 2020" "Scars_Healing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Y:/OneDrive VAQR_8066/OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség/Iskola/Prog2/NHF/Scars_Healing/Player.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'String\&.h'\fP
.br
\fC#include 'Enemy\&.h'\fP
.br
\fC#include 'Entity\&.h'\fP
.br
\fC#include 'InfoPreset\&.h'\fP
.br
\fC#include 'Storage\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlayer\fP"
.br
.RI "\fBPlayer\fP Class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Scars_Healing from the source code\&.
