.TH "Y:/OneDrive VAQR_8066/OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség/Iskola/Prog2/NHF/Scars_Healing/Storage.cpp" 3 "Sat May 2 2020" "Scars_Healing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Y:/OneDrive VAQR_8066/OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség/Iskola/Prog2/NHF/Scars_Healing/Storage.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Storage\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Scars_Healing from the source code\&.
