.TH "Y:/OneDrive VAQR_8066/OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség/Iskola/Prog2/NHF/Scars_Healing/Storage.h" 3 "Sat May 2 2020" "Scars_Healing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Y:/OneDrive VAQR_8066/OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség/Iskola/Prog2/NHF/Scars_Healing/Storage.h
.SH SYNOPSIS
.br
.PP
\fC#include 'String\&.h'\fP
.br
\fC#include 'Item\&.h'\fP
.br
\fC#include 'GenericArray\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStorage\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Scars_Healing from the source code\&.
