.TH "Y:/OneDrive VAQR_8066/OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség/Iskola/Prog2/NHF/Scars_Healing/String.cpp" 3 "Sat May 2 2020" "Scars_Healing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Y:/OneDrive VAQR_8066/OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség/Iskola/Prog2/NHF/Scars_Healing/String.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include 'memtrace\&.h'\fP
.br
\fC#include 'String\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_CRT_SECURE_NO_WARNINGS\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, \fBString\fP &str)"
.br
.RI "Writes out \fBString\fP to outputstream\&. "
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &is, \fBString\fP &s0)"
.br
.RI "Reads in \fBString\fP from inputstream\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _CRT_SECURE_NO_WARNINGS"

.SH "Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & os, \fBString\fP & str)"

.PP
Writes out \fBString\fP to outputstream\&. 
.SS "std::istream& operator>> (std::istream & is, \fBString\fP & s0)"

.PP
Reads in \fBString\fP from inputstream\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Scars_Healing from the source code\&.
