.TH "Y:/OneDrive VAQR_8066/OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség/Iskola/Prog2/NHF/Scars_Healing/test.h" 3 "Sat May 2 2020" "Scars_Healing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Y:/OneDrive VAQR_8066/OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség/Iskola/Prog2/NHF/Scars_Healing/test.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include 'Item\&.h'\fP
.br
\fC#include 'Player\&.h'\fP
.br
\fC#include 'Enemy\&.h'\fP
.br
\fC#include 'IniGame\&.h'\fP
.br
\fC#include 'Actions\&.h'\fP
.br
\fC#include 'Storage\&.h'\fP
.br
\fC#include 'GenericArray\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest\fP ()"
.br
.RI "Basic Constructing tests\&. "
.ti -1c
.RI "void \fBiniTest\fP ()"
.br
.RI "Initiates everything, then deletes it xd\&. "
.ti -1c
.RI "void \fBiniWSTest\fP (\fBGenericArray\fP< \fBItem\fP > &WSItems)"
.br
.RI "Tests if iniWS worked properly\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void iniTest ()"

.PP
Initiates everything, then deletes it xd\&. 
.SS "void iniWSTest (\fBGenericArray\fP< \fBItem\fP > & WSItems)"

.PP
Tests if iniWS worked properly\&. 
.SS "void test ()"

.PP
Basic Constructing tests\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Scars_Healing from the source code\&.
