.TH "Y:/OneDrive VAQR_8066/OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség/Iskola/Prog2/NHF/Scars_Healing/WeaponShield.txt" 3 "Sat May 2 2020" "Scars_Healing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Y:/OneDrive VAQR_8066/OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség/Iskola/Prog2/NHF/Scars_Healing/WeaponShield.txt
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Sword Of Blaise This epic sword lets you change the \fBworld\fP"
.br
.ti -1c
.RI "Sword Of Blaise This epic sword lets you change the but you have to let it guide your way Winston s Blade This Blade may not be the best in dealing \fBdamage\fP"
.br
.ti -1c
.RI "Sword Of Blaise This epic sword lets you change the but you have to let it guide your way Winston s Blade This Blade may not be the best in dealing but its compact size makes you soo \fBmobile\fP"
.br
.ti -1c
.RI "Sword Of Blaise This epic sword lets you change the but you have to let it guide your way Winston s Blade This Blade may not be the best in dealing but its compact size makes you soo that you suffer from much less \fBdamage\fP Suffering of The Past This Weapon has incredible devastating power in strong hands Shield of The Immortal Soul A \fBshield\fP"
.br
.ti -1c
.RI "Sword Of Blaise This epic sword lets you change the but you have to let it guide your way Winston s Blade This Blade may not be the best in dealing but its compact size makes you soo that you suffer from much less \fBdamage\fP Suffering of The Past This Weapon has incredible devastating power in strong hands Shield of The Immortal Soul A which defends you soul huh Sounds \fBnice\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Sword Of Blaise This epic sword lets you change the but you have to let it guide your way Winston s Blade This Blade may not be the best in dealing damage"

.SS "Sword Of Blaise This epic sword lets you change the but you have to let it guide your way Winston s Blade This Blade may not be the best in dealing but its compact size makes you soo mobile"

.SS "Sword Of Blaise This epic sword lets you change the but you have to let it guide your way Winston s Blade This Blade may not be the best in dealing but its compact size makes you soo that you suffer from much less \fBdamage\fP Suffering of The Past This Weapon has incredible devastating power in strong hands Shield of The Immortal Soul A which defends you soul huh Sounds nice"

.SS "Sword Of Blaise This epic sword lets you change the but you have to let it guide your way Winston s Blade This Blade may not be the best in dealing but its compact size makes you soo that you suffer from much less \fBdamage\fP Suffering of The Past This Weapon has incredible devastating power in strong hands Shield of The Immortal Soul A shield"

.SS "Sword Of Blaise This epic sword lets you change the world"

.SH "Author"
.PP 
Generated automatically by Doxygen for Scars_Healing from the source code\&.
